# Generated by Django 2.2 on 2022-01-15 14:02

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_auto_20220115_1256'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 15, 14, 2, 12, 862230, tzinfo=utc), verbose_name='Creation project'),
        ),
    ]
