# Generated by Django 2.2 on 2022-01-15 12:56

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_news'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 15, 12, 56, 21, 831655, tzinfo=utc), verbose_name='Date of creation'),
        ),
    ]
