# Generated by Django 2.2 on 2022-01-19 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_auto_20220115_1402'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70, verbose_name='Name')),
                ('email', models.EmailField(max_length=70, verbose_name='Email')),
                ('phone', models.CharField(max_length=30, verbose_name='Phone')),
                ('subject', models.CharField(max_length=400, verbose_name='Subject')),
                ('message', models.CharField(max_length=100, verbose_name='Message')),
            ],
        ),
    ]
